apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    from_chassis: 'True'
  labels:
    app: 'datahub-metadata-sync'
    name: 'datahub-metadata-sync-pipeline'
  name: 'datahub-metadata-sync-pipeline'
  namespace: ci-cd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/viaacode/datahub-metadata-sync.git
    sourceSecret:
      name: github
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 10
  triggers: []
status:
  lastVersion: 0
